id: dk.fhir.ig.dk-medcom-core
canonical: http://medcomfhir.dk/fhir/dk-medcom-core
name: MedComCore
title: "Danish MedCom Core"
description: Danish MedCom Core IG
status: active
version: "2.0.0"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 
    uri: https://hl7.dk/fhir/core/1.1.0/
    version: 1.1.0
  dk.fhir.ig.dk-medcom-terminology: current

menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-juristiction: true
  apply-publisher: true
