title: "MedCom Core Profiles in FHIR"
description: "This page includes content about MedCom Core profiles"
logo: /assets/images/MedCom+HL7FHIR_4.png
description: "MedCom standard based on HL7 FHIR"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
version: "Version 1.0.0-alpha.1"
fhir_version: "FHIR®© R4"
releasenote: https://github.com/medcomdk/dk-medcom-core/releases
thisurl: https://medcomdk.github.io/dk-medcom-core/
menuurl_item1: https://medcomdk.github.io/MedComLandingPage/
menutxt_item1: MedCom FHIR®© LandingPage